### ISSUE TITLE
Add `help` function

### ISSUE THREAD

**Issue by oblique** [PaddiM8/kalk#10]
It would be nice to have `help()` function that will print some kind of documentation and also show a list of supported functions.

**Comment by PaddiM8** [comment]
Yess, I totally forgot about this.

**Comment by PaddiM8** [comment]
Done!

**Comment by oblique** [comment]
I meant a `help` command within the interactive interface. For example I want to be able to see a list of the supported commands (https://github.com/PaddiM8/kalk/blob/master/kalk/src/prelude.rs), the operators that you support, maybe some examples, etc.

**Comment by PaddiM8** [comment]
Hm, there are quite a lot of functions though. I wonder how readable it would be to print them all out, since I'd want a description of them as well. I'm thinking it could be more convenient to have a separate cli subcommand for that, so that you could grep on it and such. Eg. `kalk functions`

**Comment by oblique** [comment]
Maybe you can use pager, like `less`.

**Comment by PaddiM8** [comment]
It would actually be quite neat to have that integrated with the REPL (if even practically doable with rust)... But I also want kalk to also work as a "normal" command-line program, so it could end up being a bit scattered. I'll have to think a bit more about this.

**Comment by shilangyu** [comment]
+1 for implementing the help function on the CLI level

**Comment by PaddiM8** [comment]
You can now type `help` into the REPL, and it will show you instructions, including all the functions and constants.
