### ISSUE TITLE
Consider using a more robust CLI arguments parser

### ISSUE THREAD

**Issue by shilangyu** [PaddiM8/kalk#12]
Currently when I run `kalk help` (out of habit) I get a weird error of `Undefined variable: 'h'.`. I think switching to a ready solution would greatly benefit future development.

Something like [Clap](https://github.com/clap-rs/clap) requires minimal setup while providing a lot of great features (like generating shell completions which are hard to maintain by hand). This will add to compile time though so it is worth thinking about it.

I am willing to help with the transition.

**Comment by PaddiM8** [comment]
I have been planning to do this eventually, but yeah I am a bit worried about compile times/binary size since the cli arguments are so simple. Clap is probably a good choice anyway though. I will look into it.

**Comment by matematikaadit** [comment]
If you're worried about compile times/binary size, there are a few alternatives.

Here are some comparisons taken from [pico-args' README](https://github.com/RazrFalcon/pico-args#alternatives)


|                        | null    | `pico-args` | `clap`   | `gumdrop` | `structopt` | `argh`      |
|------------------------|---------|-------------|----------|-----------|-------------|-------------|
| Binary overhead        | 0KiB    | 18.6KiB     | 379.8KiB | 21.9KiB   | 379.6KiB    | **17.1KiB** |
| Build time             | 0.1s    | **0.5s**    | 5.4s     | 7.7s      | 15.3s       | 6.0s        |
| Number of dependencies | 0       | **0**       | 12       | 5         | 25          | 12          |
| Tested version         | -       | 0.3.3       | 2.33.1   | 0.8.0     | 0.3.14      | 0.1.3       |

Links:

- [pico-args](https://crates.io/crates/pico-args)
- [clap](https://crates.io/crates/clap)
- [gumdrop](https://crates.io/crates/gumdrop)
- [structopt](https://crates.io/crates/structopt)
- [argh](https://crates.io/crates/argh)

**Comment by PaddiM8** [comment]
@matematikaadit Thank you for this!

**Comment by PaddiM8** [comment]
Ended up going with seahorse!
