### ISSUE TITLE
Calculator is wrong

### ISSUE THREAD

**Issue by cloudhead** [PaddiM8/kalk#15]
![2020-10-11-010030_248x93_scrot](https://user-images.githubusercontent.com/40774/95666846-1e699780-0b5e-11eb-9ca3-f142a87785e0.png)
:thinking:

**Comment by PaddiM8** [comment]
Hm, this does not happen on my end. I get the correct answer. Do you have the newest version installed? I remember fixing something like this a while ago. Well, there are still some slight float rounding errors, but I'm not sure how to fix those.

**Comment by cloudhead** [comment]
Thanks, now I'm getting `0.14999999999999` which is definitely closer to the truth.
