### ISSUE TITLE
Typing a word, followed by a space crashes the program

### ISSUE THREAD

**Issue by Ewpratten** [PaddiM8/kalk#16]
How to reproduce:

 1) Open `kalk`
 2) Type `test ` (notice the trailing space)
 3) Press <kbd>enter</kbd>

The error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', kalk/src/lexer.rs:80:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    18396 abort (core dumped)  ./kalk_cli
```

Version: `0.1.10`

**Comment by PaddiM8** [comment]
Oh yeah, I'm getting this too apparently. Should be fixed now, thanks a lot!
