### ISSUE TITLE
request for input file format 

### ISSUE THREAD

**Issue by muralikodali** [PaddiM8/kalk#17]
I have tried some formats, which gave error as shown below :  

```
hread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }', kalk/src/parser.rs:477:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: “./kalk -i  maths.txt” terminated by signal SIGABRT (Abort)
```

input file format for calculations and variables requested. i have not found any related information in **README**.

**Comment by PaddiM8** [comment]
What is inside the file?

**Comment by muralikodali** [comment]
i have no good knowledge of maths and physics formulas.

i simply tested with the input as shown below. 

a = 23
b = 56
sum (a,b)

**Comment by PaddiM8** [comment]
Ah, that explains it. To add numbers you simply do `a + b`, the `sum` function is like sigma, and can't be used like that. It should, however, do better error reporting with this, so thank you for finding this.
