### ISSUE TITLE
Feature request: Offer prebuilt packages

### ISSUE THREAD

**Issue by NJdevPro** [PaddiM8/kalk#20]
Not anyone has a Rust compiler installed.

Consider offering prebuilt packages for Linux/Windows/MacOS ?

**Comment by PaddiM8** [comment]
Prebuilt binaries are available [here](https://github.com/PaddiM8/kalk/releases) and [on the website](https://kalk.netlify.app). In the future I'd also like to create integrate it with package managers for different Linux distros, when I have time.
