### ISSUE TITLE
Enhancement request: configuration file or environment variable to disable startup banner

### ISSUE THREAD

**Issue by kseistrup** [PaddiM8/kalk#29]
When launched without any arguments, `kalk` will write a banner and a help hint to standard output. This is counter productive when `kalk` is used as a filter, because you cannot easily use the output from kalk in a pipe — even when output is a file, the banner/help is irrelevant.

Without thinking it through completely, I think `kalk` could just check if stdin and stdout are TTYs (`isatty(3)`) and only display banner/help if they both are: when reading expressions from stdin, stdin is not a TTY, and when writing to a pipe or a file, stdout is not a TTY.

**Comment by PaddiM8** [comment]
Yeah I just realised this from your other issue as well, this should definitely be fixed. Thank you.

**Comment by PaddiM8** [comment]
Checking if stdin and stdout are TTYs seems to have done the trick :) Thanks!
