### ISSUE TITLE
Add Iverson Bracket

### ISSUE THREAD

**Issue by abrudz** [PaddiM8/kalk#32]
An [Iverson Bracket](https://en.wikipedia.org/wiki/Iverson_bracket) is simply a predicate in square brackets which evaluates to 0 if false or 1 if true. It is great for defining functions in multiple pieces, for example `f(x)=x[x<0]+x^2[x>0]`:

![image](https://user-images.githubusercontent.com/10961427/120174365-eacaa300-c1fc-11eb-98e0-a221cbf947c8.png)

**Comment by PaddiM8** [comment]
That's pretty cool, I've been looking for a way to express something like this! I'll look into it.

**Comment by abrudz** [comment]
If you like that, and Unicode symbols, then you might like [APL](https://apl.wiki)

**Comment by PaddiM8** [comment]
> If you like that, and Unicode symbols, then you might like [APL](https://apl.wiki)

APL seems fun! Maybe I'll try it some day.

Also, if I implement Iverson brackets, it might also be useful to be able to do recursion... That could actually be pretty useful

**Comment by PaddiM8** [comment]
There, seems to work now! Having comparison operators will be useful for other features as well.

```
>> x = 1/3
>> [0 < x ≤ 1/3]*π + [x ≠ 1]
4.1415926536
```
