### ISSUE TITLE
Add piecewise functions

### ISSUE THREAD

**Issue by abrudz** [PaddiM8/kalk#33]
For example
![image](https://user-images.githubusercontent.com/10961427/120177835-bbb63080-c200-11eb-8906-af580eff320a.png)
could be written as
```
f(x) = {-x-x if x≤-3; x+3 if -3≤x≤0; 3-2x if 0≤x≤3; 0.5x-4.5 if 3≤x}
```
or:
```
f(x) = {x≤-3: -x-x; -3≤x≤0: x+3; 0≤x≤3: 3-2x; 3≤x: 0.5x-4.5}
```

**Comment by PaddiM8** [comment]
Yeah this should be a thing. Might even be possible to have it span multiple lines. The desktop program techncially already lets you write multi-line expressions if you press enter before closing a bracket. Could end up being quite readable!

**Comment by PaddiM8** [comment]
![grafik](https://user-images.githubusercontent.com/19822996/120221539-deffd080-c23e-11eb-8416-511a0da40ef5.png)

Looks like this right now. Eventually I also want to format it like this automatically (well, on the web version only probably), and make semicolons optional when it is spanned over several lines.

**Comment by abrudz** [comment]
Cool. So does this work?
```f(x)={
  1 if x≤1
  f(x-1)+f(x-2) if x>1
}
```

**Comment by PaddiM8** [comment]
> Cool. So does this work?
> 
> ```
> f(x)={
>   1 if x≤1
>   f(x-1)+f(x-2) if x>1
> }
> ```


Not yet, but that's actually the next thing I'm planning to implement, if things go as planned! (just added `otherwise` as well)

**Comment by PaddiM8** [comment]
Seems to be working fairly well now from what I can tell. Your example worked, and I was able to make a function to get fibonacci numbers! You have been very helpful, thank you.

Because of the nature of this kind of change, I'll make sure it gets tested a bit more before I push it.

**Comment by PaddiM8** [comment]
cf869358f29fa55adc217415796d3768e4964069  
68e07699422d877d523860fcb03d806ed55006e0
