### ISSUE TITLE
Use proper summation symbol

### ISSUE THREAD

**Issue by abrudz** [PaddiM8/kalk#42]
Currently, Greek letter Sigma is used: `Σ`

It may look better to use the taller N-ary summation symbol: `∑` 

Similarly, product could use `∏` rather than `Π`

**Comment by PaddiM8** [comment]
Oh I see! The summation symbol looks a bit strange with the current font(s), but I noticed they seem to look *really* good with just `serif` for me. I now made it possible to use both, and use the proper summation symbol by default on the web version (where it's possible to control the font), for now.
