### ISSUE TITLE
Remember last result?

### ISSUE THREAD

**Issue by DianaNites** [PaddiM8/kalk#6]
It'd be neat if it remembered the previous result, so that this would work

```
>> 1 + 1
2
>> + 1
3
```

Or, probably simpler, store it automatically in a `_` variable. Pythons REPL does this, for example.

```
>> 1 + 1
2
>> _ + 1
3
```

**Comment by PaddiM8** [comment]
Ah yes, I will absolutely do this when I have time!

**Comment by PaddiM8** [comment]
This should work now, I just pushed it to master! I chose to call it `ans`.
