### ISSUE TITLE
Ability to support oneliner expressions followed by a semicolon

### ISSUE THREAD

**Issue by dmilith** [PaddiM8/kalk#8]
Example use case:

`echo "x=1; sin(x)+1"` | kalk_cli
(empty result)

instead of

`echo "x=1\n sin(x)+1" | kalk_cli`

**Comment by PaddiM8** [comment]
Good idea! Will add this after units.

**Comment by PaddiM8** [comment]
Alright, I pushed it to master just now. It seems to work well. Let me know if there are any issues with it and I'll reopen the issue!
